Template.MVC5/Controllers/AssessmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AbantwanaWebMaster.BusinessLogic;
using AbantwanaWebMaster.Model;
using ExcelDataReader;
using PagedList;

namespace AbantwanaWebMaster.MVC5.Controllers
{
    public class AssessmentController : Controller
    {
       // YearBussiness business = new YearBussiness();
        // GET: LeaveTypes
        SubjectBusiness SB = new SubjectBusiness();
        GradeBussiness gb = new GradeBussiness();
        LearnerProfileBusiness lpb = new LearnerProfileBusiness();
        YearBussiness yb = new YearBussiness();
        AssessmentBussiness ab=new AssessmentBussiness();
        ClassroomBusiness cb = new ClassroomBusiness();
        termBussiness tb = new termBussiness();

        public ActionResult GradeIndex()
        {
            return View(gb.getGrade());
        }
        //public ActionResult bulkInsert()
        //{
        //    return View();
        //}

        public ActionResult Index(int subjectId, int gradeId, int yearId, int termId)
        {
            ViewBag.subjectId = subjectId;
            ViewBag.gradeId = gradeId;
            ViewBag.yearId = yearId;
            ViewBag.termId = termId;
            ViewBag.subjectName = SB.GetSubjects().Where(i => i.subjectId == subjectId).Select(o => o.subjectName).FirstOrDefault();
            ViewBag.gradeName = gb.getGrade().Where(i => i.gradeId == gradeId).Select(o => o.gradeName).FirstOrDefault();
            ViewBag.year = yb.getYear().Where(i => i.yearId == yearId).Select(o => o.year).FirstOrDefault();
            ViewBag.name = tb.getTerm().Where(i => i.termId == termId).Select(o => o.name).FirstOrDefault();
            List<Assessment> l = ab.getAssoo(subjectId, gradeId, yearId, termId);
            int intPage = 1;
            int intPageSize = 5;
            int intTotalPageCount = 0;
            //LeaveRequest nm = new LeaveRequest();
            // nm.LeaveRequests = leaveReq.getLeaveReqs();

            var _UserDTOAsIPagedList =
                    new StaticPagedList<Assessment>
                    (
                        l, intPage, intPageSize, intTotalPageCount
                        );
            
            return View(_UserDTOAsIPagedList);
        }

        // GET: assessment/Create
        public ActionResult Create(int subjectId, int gradeId, int yearId, int termId)
        {
            ViewBag.subjectName = SB.GetSubjects().Where(i => i.subjectId == subjectId).Select(o => o.subjectName).FirstOrDefault();
            ViewBag.gradeName = gb.getGrade().Where(i => i.gradeId == gradeId).Select(o => o.gradeName).FirstOrDefault();
            ViewBag.year = yb.getYear().Where(i => i.yearId == yearId).Select(o => o.year).FirstOrDefault();
            ViewBag.name = tb.getTerm().Where(i => i.termId == termId).Select(o => o.name).FirstOrDefault();
            Assessment a = new Assessment();
            a.termId = termId;
            a.subjectId = subjectId;
            a.yearId = yearId;
            a.gradeId = gradeId;
            return View(a);
        }
        //public ActionResult CaptureMark(int subjectId, int yearId, int termId,int assessmentId,int classRoomId)
        //{
        //    ViewBag.subjectId = subjectId;
        //    var gradeId = cb.GetgradeId(classRoomId);
        //    ViewBag.gradeId = gradeId;
        //    ViewBag.yearId = yearId;
        //    ViewBag.termId = termId;
        //    ViewBag.subjectName = SB.GetSubjects().Where(i => i.subjectId == subjectId).Select(o => o.subjectName).FirstOrDefault();
        //    ViewBag.className = cb.GetClassrooms().Where(i => i.classRoomId == classRoomId).Select(o => o.className).FirstOrDefault();
        //    ViewBag.year = yb.getYear().Where(i => i.yearId == yearId).Select(o => o.year).FirstOrDefault();
        //    ViewBag.name = tb.getTerm().Where(i => i.termId == termId).Select(o => o.name).FirstOrDefault();
        //    ViewBag.assname = ab.getAssess().Where(i => i.assessmentId == assessmentId).Select(o => o.assessmentName).FirstOrDefault();

        //    return View(ab.GetAllLearnersByClassRoom(yearId,subjectId,gradeId,classRoomId,assessmentId,termId));
        //}
        public ActionResult CaptureMark(int subjectId, int yearId, int termId,int assessmentId,int classRoomId)
        {
            ViewBag.subjectId = subjectId;
            var gradeId = cb.GetgradeId2(classRoomId);
            ViewBag.gradeId = gradeId;
            ViewBag.yearId = yearId;
            ViewBag.termId = termId;
            ViewBag.subjectName = SB.GetSubjects().Where(i => i.subjectId == subjectId).Select(o => o.subjectName).FirstOrDefault();
            ViewBag.className = cb.GetClassrooms().Where(i => i.classRoomId == classRoomId).Select(o => o.className).FirstOrDefault();
            ViewBag.year = yb.getYear().Where(i => i.yearId == yearId).Select(o => o.year).FirstOrDefault();
            ViewBag.name = tb.getTerm().Where(i => i.termId == termId).Select(o => o.name).FirstOrDefault();
            ViewBag.assname = ab.getAssess().Where(i => i.assessmentId == assessmentId).Select(o => o.assessmentName).FirstOrDefault();
           
            return View(ab.GetAllLearnersByClassRoom(yearId,subjectId,gradeId,classRoomId,assessmentId,termId));
        }
        //[HttpPost]
        public ActionResult bulkInsert(int subjectId, int yearId, int termId,int assessmentId,int classRoomId)
        {
            ViewBag.subjectId = subjectId;
            var gradeId = cb.GetgradeId2(classRoomId);
            ViewBag.gradeId = gradeId;
            ViewBag.yearId = yearId;
            ViewBag.termId = termId;
            ViewBag.subjectName = SB.GetSubjects().Where(i => i.subjectId == subjectId).Select(o => o.subjectName).FirstOrDefault();
            ViewBag.className = cb.GetClassrooms().Where(i => i.classRoomId == classRoomId).Select(o => o.className).FirstOrDefault();
            ViewBag.year = yb.getYear().Where(i => i.yearId == yearId).Select(o => o.year).FirstOrDefault();
            ViewBag.name = tb.getTerm().Where(i => i.termId == termId).Select(o => o.name).FirstOrDefault();
            ViewBag.assname = ab.getAssess().Where(i => i.assessmentId == assessmentId).Select(o => o.assessmentName).FirstOrDefault();
           
            return View(ab.GetAllLearnersByClassRoom(yearId,subjectId,gradeId,classRoomId,assessmentId,termId).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult bulkInsert(HttpPostedFileBase upload, LearnerAssessment learner)
        {
            List<LearnerAssessment> lio = new List<LearnerAssessment>();
            if (upload != null && upload.ContentLength > 0)
            {
                // ExcelDataReader works with the binary Excel file, so it needs a FileStream
                // to get started. This is how we avoid dependencies on ACE or Interop:
                Stream stream = upload.InputStream;

                IExcelDataReader reader = null;


                if (upload.FileName.EndsWith(".xls"))
                {
                    reader = ExcelReaderFactory.CreateBinaryReader(stream);
                }
                else if (upload.FileName.EndsWith(".xlsx"))
                {
                    reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                }
                else
                {
                    ModelState.AddModelError("File", "This file format is not supported");
                    return View();
                }
                int fieldcount = reader.FieldCount;
                int rowcount = reader.RowCount;
                DataTable dt = new DataTable();
                DataRow row;
                DataTable dt_ = new DataTable();
                try
                {
                    dt_ = reader.AsDataSet().Tables[0];
                    for (int i = 0; i < dt_.Columns.Count; i++)
                    {
                        dt.Columns.Add(dt_.Rows[0][i].ToString());
                    }
                    int rowcounter = 0;
                    for (int row_ = 1; row_ < dt_.Rows.Count; row_++)
                    {
                        row = dt.NewRow();


                        if(count(learner, Convert.ToInt32(dt_.Rows[row_][0]))>0)
                        {
                            learner.learnerId = Convert.ToInt32(dt_.Rows[row_][0]);
                             learner.Name = dt_.Rows[row_][2].ToString();
                            learner.AssessmentMark= Convert.ToInt32(dt_.Rows[row_][3]);
                        }
                        lio.Add(learner);
                        //Students students = new Students();
                        //students.Name = dt_.Rows[row_][1].ToString();
                        //students.Country = dt_.Rows[row_][2].ToString();
                        //db.Students.Add(students);
                        //db.SaveChanges();


                        for (int col = 0; col < dt_.Columns.Count; col++)
                        {
                            row[col] = dt_.Rows[row_][col].ToString();
                            rowcounter++;
                        }
                        dt.Rows.Add(row);
                    }


                foreach (var ih in lio)
                {
                    ViewBag.subjectName = SB.GetSubjects().Where(i => i.subjectId == ih.subjectId).Select(o => o.subjectName).FirstOrDefault();
                    ViewBag.className = cb.GetClassrooms().Where(i => i.classRoomId == ih.classID).Select(o => o.className).FirstOrDefault();
                    ViewBag.year = yb.getYear().Where(i => i.yearId == ih.yearId).Select(o => o.year).FirstOrDefault();
                    ViewBag.name = tb.getTerm().Where(i => i.termId == ih.termId).Select(o => o.name).FirstOrDefault();
                    ViewBag.assname = ab.getAssess().Where(i => i.assessmentId == ih.assessmentId).Select(o => o.assessmentName).FirstOrDefault();

Template.MVC5/Controllers/ClassroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AbantwanaWebMaster.BusinessLogic;
using AbantwanaWebMaster.Model;
namespace AbantwanaWebMaster.MVC5.Controllers
{
    public class ClassroomController : Controller
    {
       
        ClassroomBusiness ClassB = new ClassroomBusiness();
        LearnerProfileBusiness Lp = new LearnerProfileBusiness();
        staffRegBusiness sf = new staffRegBusiness();
        GradeBussiness gb = new GradeBussiness();
        YearBussiness yb = new YearBussiness();
        public ActionResult Index()
        {
            return View(ClassB.GetClassrooms());
        } 
        
        public ActionResult Create()
        {
            
            ViewBag.staffId = new SelectList(sf.GetStaffMembers(), "staffMemberId", "StaffMemberName");
            ViewBag.graddId = new SelectList(gb.getGrade(), "gradeId", "gradeName");
            return View();
        }
        public ActionResult LearnerAllocation(int id,string l)
        {
            if (l==null)
            {
                ViewBag.classRoomId = new SelectList(ClassB.GetClassroomsByLearnerID(id), "classroomid", "className");
            }
            else
            {
                ViewBag.classRoomId = new SelectList(ClassB.GetClassrooms(), "classroomid", "className");
            }
            
            ViewBag.yearId = new SelectList(yb.getYear(), "yearId", "year");
            YearLearnerClassRoom ylc = new YearLearnerClassRoom();
            ylc.learnerId = id;
            return View(ylc);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult LearnerAllocation(YearLearnerClassRoom x)
        {
            

            ViewBag.classRoomId = new SelectList(ClassB.GetClassroomsByLearnerID(x.learnerId), "classroomid", "className");
            ViewBag.yearId = new SelectList(yb.getYear(), "yearId", "year");

            if (ModelState.IsValid)
            {
                if (ClassB.GetClassrooms().Where(p => p.graddId ==ClassB.GetGradeId(x.yearId,x.learnerId)).Count()!=0)
                {
                    ModelState.AddModelError("", "Learner has been Allocated before !!");

                }
                else
                {

                    ClassB.addYearLearnerClassroom(x);
                    Fees y = new Fees();
                    y.classRoomId = x.classRoomId;
                    y.learnerId = x.learnerId;
                    ClassB.addFees(y);
                    return RedirectToAction("AppSuccess","LearnerProfile");
                }
                return View(x);

            }

            return View(x);
        }

        public JsonResult GetLearners()
        {

            return new JsonResult { Data = Lp.GetAllLearners(0), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create(ClassRoom x)
        {
            ViewBag.staffId = new SelectList(sf.GetStaffMembers(), "staffMemberId", "StaffMemberName");
            ViewBag.graddId = new SelectList(gb.getGrade(), "gradeId", "gradeName");
    

            if (ModelState.IsValid)
            {
               if( ClassB.GetClassrooms().Where(p=>p.className.ToLower()==x.className.ToLower()).Count()!=0)
                {
                    ModelState.AddModelError("", "Class Name Already Exist");

                }
                else if( ClassB.GetClassrooms().Where(p=> p.roomnumber.ToLower() == x.roomnumber.ToLower()).Count()!=0)
                {
                    ModelState.AddModelError("", "Room Has been allocated before");

                }
                else if( ClassB.GetClassrooms().Where(p=> p.staffId == x.staffId).Count()!=0)
                {
                    ModelState.AddModelError("", "Teacher Already allocated To Another Class");

                }
                else
                {
                    ClassB.addClarroom(x);
                    return RedirectToAction("Index");
                }
                return View(x);
                
            }

            return View(x);
        }
    }
}

Template.MVC5/Views/Subject/Create.cshtml
@model AbantwanaWebMaster.Model.Subject

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Subject</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.subjectName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.subjectName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.subjectName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}


<div class="btn-group">
    <a class="btn btn-default" href="@Url.Action("Index", "Subject")">
      
        Back To List
    </a>
</div>

Template.MVC5/Views/Subject/Delete.cshtml
@model AbantwanaWebMaster.Model.Subject

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Criterion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Criterion)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Template.MVC5/Views/Subject/Details.cshtml
@model AbantwanaWebMaster.Model.Subject

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Subject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Criterion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Criterion)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SubjectID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Template.MVC5/Views/Subject/GradeSubjectIndex.cshtml
@*@model IEnumerable<AbantwanaWebMaster.Model.Subject>*@

@{
    ViewBag.Title = "Index";
}

@model PagedList.IPagedList<AbantwanaWebMaster.Model.GradeSubject>
@using PagedList.Mvc
@using PagedList
@{
    ViewBag.Title = "Grade Subject";
}


<html>
<head>
    @using GridMvc.Html
    @{
        var grid = new WebGrid(Model);
    }

    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    @*@*<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />*@
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>


    <style>
        .webgrid-table {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size: 1.2em;
            width: 100%;
            display: table;
            border-collapse: separate;
            border: solid 1px #98BF21;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #98BF21;
                padding: 3px 7px 2px;
            }
    </style>
</head>
<body>
    <center>
        <div style="background-color:whitesmoke; height:37px;width:85% ;font-size:15px;">

            <h2>Grade @ViewBag.GradeName Subjects</h2>


        </div>

        <div class="card shadow mb-4" style="background-color:aliceblue; width:85%">
            <div class="card-header ">


                <p>
                    <div class="btn-group">
                        <a class="btn btn-send" href="@Url.Action("subjectAllocation", "Subject")">
                            <i class="fad fa-file-alt"></i>
                            Linking Subject To Grade
                        </a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-success" href="@Url.Action("GradeIndex", "Assessment")">
                            <i class="fad fa-file-alt"></i>
                            Grades
                        </a>
                    </div>

                </p>



            </div>
            <div id="gridContent" style=" padding:20px; ">
                <table class="table table-bordered" id="dataTable" width="100" cellspacing="0">
                    <thead style="font-size:medium;">

                        <tr>
                            <th>
                                @Html.DisplayName("Subject")

                            </th>
                            <th>
                                @Html.DisplayName("Requirement")

                            </th>
                            <th>
                                @Html.DisplayName("Status")
                            </th>
                            <th>
                                @Html.DisplayName("Update")
                            </th>
                            <th>
                                @Html.DisplayName(" Assessment Year")
                            </th>

                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tbody>
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.subjectName)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.requirement)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.active)
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-warning" href="@Url.Action("GradeSubjectUpdate", "Subject", new { subjectId=item.subjectId,gradeId=item.gradeId },null)">
                                            <span class="icon_lightbulb_alt"></span>
                                            Update Subject
                                        </a>
                                    </div>
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-primary" href="@Url.Action("YearIndex", "Subject", new { subjectId=item.subjectId,gradeId=item.gradeId },null)">
                                            <span class="icon_lightbulb_alt"></span>
                                            Assessment Year
                                        </a>
                                    </div>
                                </td>


                            </tr>
                        </tbody>
                    }

                </table>
            </div>

            <div style="text-align: center">
                <p>
                    @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                </p>
                <p style="margin-top: -25px">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </p>
            </div>

</center>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/gridmvc.min.js"></script>

</body>
</html>

Template.MVC5/Views/Subject/TermIndex.cshtml
@model IEnumerable<AbantwanaWebMaster.Model.Term>

@{
    ViewBag.Title = "Terms";
}


<html>
<head>
    @using GridMvc.Html
    @{
        var grid = new WebGrid(Model);
    }

    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    @*@*<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />*@
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>


    <style>
        .webgrid-table {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size: 1.2em;
            width: 100%;
            display: table;
            border-collapse: separate;
            border: solid 1px #98BF21;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #98BF21;
                padding: 3px 7px 2px;
            }
    </style>
</head>
<body>
    <center>
        <div style="background-color:whitesmoke; height:37px;width:85% ;font-size:15px;">

            <h2>Terms</h2>

        </div>

        <div class="card shadow mb-4" style="background-color:aliceblue; width:85%">
            <div class="card-header ">
                <p>
                    @*<div class="btn-group">
            <a class="btn btn-send" href="@Url.Action("Index", "Classroom")">
                <i class="fad fa fa-home"></i>
                Home
            </a>
        </div>
        <div class="btn-group">
            <a class="btn btn-success" href="@Url.Action("Create", "Classroom")">
                <i class="fad fa-file-alt"></i>
                Add New Class
            </a>
        </div>*@

                    <div class="btn-group">
                        <a class="btn btn-send" href="@Url.Action("GradeIndex", "Assessment")">
                            <i class="fad fa-file-alt"></i>
                            Grades
                        </a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-send" href="@Url.Action("GradeSubjectIndex", "Subject",new{gradeId = ViewBag.gradeId })">
                            <i class="fad fa-file-alt"></i>
                            Subjects
                        </a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-send" href="@Url.Action("YearIndex", "Subject",new { subjectId = ViewBag.subjectId, gradeId = ViewBag.gradeId })">
                            <i class="fad fa-file-alt"></i>
                            Years
                        </a>
                    </div>




                </p>


            </div>
            <div id="gridContent" style=" padding:20px; ">

                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.name)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="@Url.Action("Index", "Assessment", new { subjectId=ViewBag.subjectId,gradeId= ViewBag.gradeId,yearId=ViewBag.yearId,termId=item.termId},null)">
                                        <span class="icon_lightbulb_alt"></span>
                                        Assessment Management
                                    </a>
                                </div>
                            </td>

                        </tr>
                    }

                </table>

            </div>
        </div>


    </center>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/gridmvc.min.js"></script>

</body>
</html>

Template.MVC5/Views/Subject/YearIndex.cshtml
@model IEnumerable<AbantwanaWebMaster.Model.Year>

@{
    ViewBag.Title = "Year";
}


<html>
<head>
    @using GridMvc.Html
    @{
        var grid = new WebGrid(Model);
    }

    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    @*@*<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />*@
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>


    <style>
        .webgrid-table {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size: 1.2em;
            width: 100%;
            display: table;
            border-collapse: separate;
            border: solid 1px #98BF21;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #98BF21;
                padding: 3px 7px 2px;
            }
    </style>
</head>
<body>
    <center>
        <div style="background-color:whitesmoke; height:37px;width:85% ;font-size:15px;">

            <h2>List Of Years</h2>

        </div>

        <div class="card shadow mb-4" style="background-color:aliceblue; width:85%">
            <div class="card-header ">
                <p>
                    @*<div class="btn-group">
            <a class="btn btn-send" href="@Url.Action("Index", "Classroom")">
                <i class="fad fa fa-home"></i>
                Home
            </a>
        </div>
        <div class="btn-group">
            <a class="btn btn-success" href="@Url.Action("Create", "Classroom")">
                <i class="fad fa-file-alt"></i>
                Add New Class
            </a>
        </div>*@


                    <div class="btn-group">
                        <a class="btn btn-send" href="@Url.Action("GradeIndex", "Assessment")">
                            <i class="fad fa-file-alt"></i>
                            Grades
                        </a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-default" href="@Url.Action("GradeSubjectIndex", "Subject",new{gradeId = ViewBag.gradeId })">
                            <i class="fad fa-file-alt"></i>
                            Subjects
                        </a>
                    </div>

                </p>


            </div>
            <div id="gridContent" style=" padding:20px; ">
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.year)
                        </th>
                        <th>
                            Assessment Term
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.year)
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="@Url.Action("TermIndex", "Subject", new { subjectId=ViewBag.subjectId,gradeId= ViewBag.gradeId,yearId=item.yearId},null)">
                                        <span class="icon_lightbulb_alt"></span>
                                        Assessment Term
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>


    </center>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/gridmvc.min.js"></script>

</body>
</html>