Template.MVC5/Controllers/LeaveTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AbantwanaWebMaster.BusinessLogic;
using AbantwanaWebMaster.Model;


namespace AbantwanaWebMaster.MVC5.Controllers
{
    public class LeaveTypesController : Controller
    {
        LeaveTypeBusiness business = new LeaveTypeBusiness();
        // GET: LeaveTypes
       
        public ActionResult Index()
        {
            return View(business.getLeaveType());
        }

        

        // GET: LeaveTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "leaveTypeID,typeName")] LeaveType leaveType)
        {
            if (ModelState.IsValid)
            {
               business.createLeaveType(leaveType);
                return RedirectToAction("Index");
            }

            return View(leaveType);
        }


       
        // GET: LeaveTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //var ig = (id||0);
            if (business.acrhiveType(id??default(int)))
            {
                return RedirectToAction("Index");
                // return HttpNotFound();
            }
            else
            {
                return HttpNotFound();
            }
           
        }

        
    }
}

Template.MVC5/Views/LeaveTypes/Create.cshtml
@model  AbantwanaWebMaster.Model.LeaveType

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LeaveType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.typeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.typeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.typeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Template.MVC5/Views/LeaveTypes/Edit.cshtml
@model AbantwanaWebMaster.Model.LeaveType

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LeaveType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.leaveTypeID)

        <div class="form-group">
            @Html.LabelFor(model => model.typeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.typeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.typeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Template.MVC5/Views/LeaveTypes/Index.cshtml
@model IEnumerable<AbantwanaWebMaster.Model.LeaveType>

@{
    ViewBag.Title = "Leave Types";
}

<h2>Types of Leaves</h2>

<p>
    @Html.ActionLink("Add Type", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.typeName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.typeName)
        </td>
        <td>
          
           
            <a href=@Url.Action("Delete", "LeaveTypes", new { id=item.leaveTypeID },null)> Delete</a>
        </td>
    </tr>
}

</table>