Template.MVC5/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AbantwanaWebMaster.Model;
using AbantwanaWebMaster.BusinessLogic;

namespace AbantwanaWebMaster.MVC5.Controllers
{
    public class StoreController : Controller
    {
        CategoryBusiness categories = new CategoryBusiness();
        //private object Customerlist;

        // GET: Store

        public ActionResult Index()
        {
            
            return View(categories.GetAllCategorys());
        }
        [ChildActionOnly]
        public ActionResult CategoryMenu()
        {
            //var categories = storeDB.Categories.ToList();
            return PartialView(categories.GetAllCategorys());

        }
        public ActionResult Browse(string category)
        {
            //var categoryModel = storeDB.Categories.Include("Items")
            //    .Single(c => c.Name == category);
            return View(categories.Browse(category));
        }
        public ActionResult Details(int id)
        {
            var Item =categories.Find(id);
            return View(categories.Find(id));
        }


        public ActionResult BrowsItem()

        {

            //Using foreach loop fill data from custmerlist to List<CustomerVM>.

            return View(categories.browserList()); //List of CustomerVM (ViewModel)

        }

    }

}

Template.MVC5/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AbantwanaWebMaster.Model;
using AbantwanaWebMaster.BusinessLogic;

namespace AbantwanaWebMaster.MVC5.Controllers
{
    //[Authorize(Users = "Ali@gmail.com,Ahmed@gmail.com")]
    public class StoreManagerController : Controller
    {
        // private  db = new ApplicationDbContext();
        StoreManagerBusiness business = new StoreManagerBusiness();
        // GET: StoreManager
        public ActionResult Index()
        {
            //var items = db.Items.Include(i => i.Category).Include(i => i.Producer);
            return View(business.itemList());
        }
        public ActionResult View1()
        {
            //var items = db.Items.Include(i => i.Category).Include(i => i.Producer);
            return View(business.itemList());
        }

        // GET: StoreManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            if (business.Find(id??default(int)) == null)
            {
                return HttpNotFound();
            }
            return View(business.Find(id??default(int)));
        }

        // GET: StoreManager/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(business.GetAllCatergory(), "CategoryId", "Name");
            //ViewBag.SupplierId = new SelectList(business.GetAllSuppliers(), "supplierID", "name");
            return View();
        }

        // POST: StoreManager/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item item, HttpPostedFileBase image1)
        {
            //var db = new ApplicationDbContext();
            if (image1 != null)
            {
                item.Picture = new byte[image1.ContentLength];
                image1.InputStream.Read(item.Picture, 0, image1.ContentLength);
            }
            if (ModelState.IsValid)
            {
                business.addNewItem(item);
               // db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.CategoryId = new SelectList(business.GetAllCatergory(), "CategoryId", "Name");
           // ViewBag.ProducerId = new SelectList(business.GetAllSuppliers(), "supplierID", "name");
            ViewBag.CategoryId = new SelectList(business.GetAllCatergory(), "CategoryId", "Name", item.CategoryId);
            //ViewBag.SupplierId = new SelectList(business.GetAllSuppliers(), "supplierID", "name", item.SupplierId);
            return View(item);
        }

        // GET: StoreManager/Edit/5
       

        // GET: StoreManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           // Item item = db.Items.Find(id);
            if (business.Find(id??default(int)) == null)
            {
                return HttpNotFound();
            }
            return View(business.Find(id ?? default(int)));
        }

        // POST: StoreManager/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int id)
        {
            

            return new JsonResult { Data = new { status = business.deleteItem(id)} };
        }

        
    }
}

Template.MVC5/Views/StoreManager/Create.cshtml
@model AbantwanaWebMaster.Model.Item
@{
    ViewBag.Title = "Create";
}

<html>
<head>

</head>
<style>

    .container {
        position: relative;
        max-width: 100%;
        margin: 0 auto;
    }


    h3 {
        color: darkblue;
        font-weight: bold;
    }

    .w3-btn {
        width: 150px;
    }


    #myBtn {
        display: none;
        position: fixed;
        bottom: 20px;
        right: 30px;
        z-index: 99;
        font-size: 18px;
        border: none;
        outline: none;
        background-color: blue;
        color: white;
        cursor: pointer;
        padding: 15px;
        border-radius: 4px;
    }

        #myBtn:hover {
            background-color: #555;
        }

    a.mybtn {
        background: red;
        color: white;
        display: inline-block;
        padding: 6px 12px 6px 12px;
        text-decoration: none;
    }

    h3 {
        font-style: oblique;
    }

    hr.new4 {
        border: 3px solid black;
    }

    form-group1 {
        align-content: left;
    }
</style>



<body>
    <center>



        @*<div class="container-fluid" style="background-color:black">*@
        <div style="background-color:">

            <div class="card shadow mb-4" style="background-color: ; width:70%">
                <div class="card-header ">
                    <div style=" font-size:15px;">

                        <div style="background-color:white; height:37px;width:100% ;font-size:15px;">

                            <h2> New Iterm</h2>
                            @*@Html.ActionLink("Back to List", "Index", null, htmlAttributes: new { @class = "btn btn-default" })

                                @Html.ActionLink("Back to List", "Index", null, htmlAttributes: new { @class = "btn btn-default" })*@
                        </div>

                        <hr class="new4">
                    </div>
                </div>
                <button onclick="topFunction()" id="myBtn" title="Go to top" style="width:5%">Top</button>
                <div class="container">

                    <div class="content" style="text-align:left">

                        @using (Html.BeginForm("Create", "StoreManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                             
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                @*<div class="form-group">
                    @Html.LabelFor(model => model.SupplierId, "SupplierId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("SupplierId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SupplierId, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ItemDesciption, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ItemDesciption, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ItemDesciption, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                @*<div class="form-group">
                    @Html.LabelFor(model => model.ItemArtUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ItemArtUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ItemArtUrl, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <input type="file" id="image1" name="image1" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-success" />
                                    </div>
                                </div>
                            </div>
                        }
                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    </div>




                </div>
            </div>

    </center>





    <script>
        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () { scrollFunction() };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                document.getElementById("myBtn").style.display = "block";
            } else {
                document.getElementById("myBtn").style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }


        //........................................................................................

    </script>

    <script type="text/javascript">
        function readfile(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#fileUpload').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>


</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Template.MVC5/Views/StoreManager/Delete.cshtml
@model AbantwanaWebMaster.Model.Item

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Producer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Template.MVC5/Views/StoreManager/Details.cshtml
@model AbantwanaWebMaster.Model.Item

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catergoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Template.MVC5/Views/StoreManager/Edit.cshtml
@model AbantwanaWebMaster.Model.Item

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemId)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProducerId, "ProducerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProducerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProducerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Template.MVC5/Views/StoreManager/Index.cshtml
@model IEnumerable<AbantwanaWebMaster.Model.Item>
@{
    ViewBag.Title = "Index";

}
<link href="~/Content/StyleSheet2.css" rel="stylesheet" />

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<script src="/Scripts/jquery-1.4.4.min.js"
        type="text/javascript"></script>

<html>
<head>
    @using GridMvc.Html
    @{
        var grid = new WebGrid(Model);
    }

    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    @*@*<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />*@
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>


    @*<link href="~/Content/bootstrap.css" rel="stylesheet" />
        <link href="~/Content/Gridmvc.css" rel="stylesheet" />
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/gridmvc.min.js"></script>

        <link href="~/Content/viewlight.css" rel="stylesheet" />*@



    <style>
        .webgrid-table {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size: 1.2em;
            width: 100%;
            display: table;
            border-collapse: separate;
            border: solid 1px #98BF21;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #98BF21;
                padding: 3px 7px 2px;
            }
    </style>
</head>
<body>
    <center>
        <div style="background-color:whitesmoke; height:37px;width:85% ;font-size:15px;">

            <h2> Iterm List </h2>

        </div>


        <div class="card shadow mb-4" style="background-color:aliceblue; width:85%; top:auto">
            <div class="card-header ">

                <p>
                    <div class="btn-group">
                        <a class="btn btn-send" href="@Url.Action("Index", "StoreManager")">
                            <i class="fad fa fa-home"></i>
                            Home
                        </a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-success" href="@Url.Action("Create", "StoreManager")">
                            <i class="fad fa-file-alt"></i>
                            Add New Item
                        </a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-primary" href="@Url.Action("Index", "Categories")">
                            <i class="fa fa-list"></i>
                            Item Categories
                        </a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-warning" href="@Url.Action("Index", "Store")">
                            <i class="fa fa-shopping-cart"></i>
                            Store
                        </a>
                    </div>
                </p>

            </div>


            @*<div class="table-responsive">*@

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Catergory")
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.ItemName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ItemDesciption)
                    </th>
                    <th>
                        Action
                    </th>

                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.catergoryName)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.ItemName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ItemDesciption)
                        </td>
                        <td>
                            <button style="background-color:orangered;width:55%;height:3%" id="hi" onclick="arch(@item.ItemId)"> Archive</button>

                           
                        </td>
                    </tr>
                }
            </table>



        </div>


        </div>

    </center>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/gridmvc.min.js"></script>

</body>
</html>









    <script>
        function arch(id) {
            if (confirm('Are you sure?')) {
                $.ajax({
                    type: 'POST',
                    url: "/StoreManager/DeleteConfirmed",
                    data: { 'id': id }, //Used to send data through HTTP request POST
                    success: function (data) {
                        if (data.status == true) {  //refresh calender if success
                            alert("Succefully Archived");
                        }
                    },
                    error: function () {
                        alert('Failed to Archived Item!')
                    }
                })
            }
        }
        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () { scrollFunction() };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                document.getElementById("myBtn").style.display = "block";
            } else {
                document.getElementById("myBtn").style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>
</body>
</html>

Template.MVC5/Views/StoreManager/View1.cshtml
@model IEnumerable<AbantwanaWebMaster.Model.Item>
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Producer.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>

        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink("Home", "Index", "Home")

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Producer.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ItemId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ItemId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ItemId })
            </td>
        </tr>
    }
</table>