Template.MVC5/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AbantwanaWebMaster.Model;
using AbantwanaWebMaster.BusinessLogic;
using PagedList;
using System.Net;

namespace AbantwanaWebMaster.MVC5.Controllers
{
   
        // GET: Leave
        public class LeaveController : Controller
        {
        LeaveReqBusiness leaveReq = new LeaveReqBusiness();
        // GET: Leave
        [Authorize(Roles = "Teacher")]
        public ActionResult CreateRequest()
            {
            ViewBag.leaveTypeID = new SelectList(leaveReq.getLeaveTypes(), "leaveTypeID", "typeName");
            return View();
            }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //var ig = (id||0);
            if (leaveReq.acrhiveType(id ?? default(int)))
            {
                return RedirectToAction("Index");
                // return HttpNotFound();
            }
            else
            {
                return HttpNotFound();
            }

        }
        public ActionResult Approve(int? id)
        {
            //Roster roster = db.rosters.Find(id);
            //EmployeeLeavel employeeLeavel = db.employeeLeavels.Find(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            return View(leaveReq.getLeaveReqs(id??default(int)));

        }
        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult CreateRequest(LeaveRequest leave)
        {
            if (ModelState.IsValid)
            {
                //leave.staffmemberId = User.Identity.;
                leaveReq.createLeaveReq(leave,User.Identity.Name);
            }
            ViewBag.leaveTypeID = new SelectList(leaveReq.getLeaveTypes(), "leaveTypeID", "typeName");
            return View();
        }
        [ChildActionOnly]
        public ActionResult leavelist()
        {
            LeaveRequest nm = new LeaveRequest();
            nm.LeaveRequests = leaveReq.getLeaveReqs();
            return PartialView("_lleavelist",nm.LeaveRequests );
        }
        public ActionResult index()
        {
            int intPage = 1;
            int intPageSize = 5;
            int intTotalPageCount = 0;
            //LeaveRequest nm = new LeaveRequest();
            // nm.LeaveRequests = leaveReq.getLeaveReqs();

            var _UserDTOAsIPagedList =
                    new StaticPagedList<LeaveRequest>
                    (
                        leaveReq.getLeaveReqs(), intPage, intPageSize, intTotalPageCount
                        );


            return View(_UserDTOAsIPagedList);
        }
        public ActionResult Teacherindex()
        {
            int intPage = 1;
            int intPageSize = 5;
            int intTotalPageCount = 0;
            //LeaveRequest nm = new LeaveRequest();
            // nm.LeaveRequests = leaveReq.getLeaveReqs();

            var _UserDTOAsIPagedList =
                    new StaticPagedList<LeaveRequest>
                    (
                        leaveReq.getLeaveReqs(User.Identity.Name), intPage, intPageSize, intTotalPageCount
                        );


            return View(_UserDTOAsIPagedList);
        }
        [HttpPost]
        public ActionResult approve(LeaveRequest leave)
        {
            try
            {
                if (leaveReq.ReplaceTeacher(leave))
                {
                    return RedirectToAction("Index");
                }
            }
            catch(Exception e)
            {
                ViewBag.Message = "approval not saved. Error: " + e.Message;
            }
            ViewBag.Message = "approval not saved Please find a replacement Teacher ";
            return View(leaveReq.getLeaveReqs(leave.requestid));
        }

        //[HttpPost]
        //public JsonResult approveLeave(LeaveRequest leave)
        //{
        //    return new JsonResult { Data = new { status = leaveReq.ReplaceTeacher(leave) } };
        //}

        public ActionResult LeaveRequestCount()
        {
            
            ViewBag.count = leaveReq.counter();
            //(db.contactUs.ToList().Where(x => x.read.Equals(false))).Count();
            return View();
        }

        [HttpPost]
        public JsonResult replaceTeacher(LeaveRequest work)
        {
            return new JsonResult { Data = new { status = leaveReq.ReplaceWithTeacher(work) } };
        }


        //[HttpPost]
        public JsonResult getStaffList(int requestid)
        {
           
            return new JsonResult { Data = leaveReq.GetResources(requestid), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

Template.MVC5/Views/shared/Create.cshtml
@using BootstrapSupport
@model Object
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset class="form-horizontal">
        <legend>@Model.GetLabel() <small>Details</small></legend>
        @foreach (var property in Model.VisibleProperties())
        {
            using(Html.ControlGroupFor(property.Name)){
                @Html.Label(property.Name.ToSeparatedWords(), new { @class = "control-label" })
                 <div class="controls">
                     @Html.Editor(property.Name, new { @class = "input-xlarge" })
                     @Html.ValidationMessage(property.Name, null, new { @class = "help-inline" })
                 </div>
            }
        }
		<div class="form-actions">
            <button type="submit" class="btn btn-primary">Save changes</button>
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn " })
          </div>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Template.MVC5/Views/shared/Index.cshtml
@using BootstrapSupport
@model System.Collections.IEnumerable   
    <h4>@Model.GetLabel() <small>Listing</small></h4>
<table class="table table-striped">
    <caption></caption>
    <thead>
        <tr>
            @foreach (var property in Model.VisibleProperties())
            {
                <th>
                    @property.GetLabel().ToSeparatedWords()
                </th>
            }
            <th></th>
        </tr>
    </thead>
    @{ int index = 0; }
    @foreach (var model in Model)
    {
        ViewData[index.ToString()] = model;
        <tr>
            @foreach (var property in model.VisibleProperties())
            {
                <td>
                    @Html.Display(index + "." + property.Name)
                </td>                    
            }
            <td>
                <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        Action
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        @{
                            @Html.TryPartial("_actions", model)                            
                            var routevalues = model.GetIdValue();  
                            <li>@Html.ActionLink("Edit", "Edit", routevalues)</li>
                            <li>@Html.ActionLink("Details", "Details", routevalues)</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Delete", "Delete", routevalues)</li>
                               
                        }
                    </ul>
                </div>

            </td>
        </tr>
            index++;
    }

</table>
<p>
    @Html.ActionLink("Create New", "Create", null, new {@class = "btn"})
</p>

Template.MVC5/Views/shared/_AnnouncementCounter.cshtml
@{
    Html.RenderAction("AnnouncementCount", "Announcement");

    //  Html.RenderAction("InboxCount", "EmailUs");
}

Template.MVC5/Views/shared/_BootstrapLayout.empty.cshtml
@using System.Web.Optimization
@using BootstrapSupport
@using NavigationRoutes
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Styles.Url("~/content/css")" rel="stylesheet"/>
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>    <link href="@Styles.Url("~/Content/css-responsive")" rel="stylesheet" type="text/css" />
    @*@RenderSection("head", required: false)*@
    @Html.Partial("_html5shiv")
    @* favicons and touch icons go here *@
</head>
<body>
    <div class="container">

        @Html.Partial("_alerts")
        @RenderBody()
        <hr>
        <footer>
            <p>&copy; Company @System.DateTime.Now.ToString("yyyy")</p>
        </footer>

    </div> <!-- container -->
    @Scripts.Render("~/js")
    @RenderSection("Scripts", required: false)
</body>
</html>

Template.MVC5/Views/shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Template.MVC5/Views/shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Template.MVC5/Views/shared/_Header.cshtml
<header class="main-header  navbar-fixed-top">
    <a href="@Url.Action("ndex", "Home")" class="logo">
        <span class="logo-mini"><b>ONS</b>KOOL</span>
        <span class="logo-lg"><b>ONSKOOL</b> </span>
    </a>


    <nav class="navbar navbar-static navbar-fixed-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>

                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="~/AdminLTE/dist/img/user.svg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="~/AdminLTE/dist/img/user.svg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            AdminLTE Design Team
                                            <small><i class="fa fa-clock-o"></i> 2 hours</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="~/AdminLTE/dist/img/user.svg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Developers
                                            <small><i class="fa fa-clock-o"></i> Today</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="~/AdminLTE/dist/img/user.svg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Sales Department
                                            <small><i class="fa fa-clock-o"></i> Yesterday</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="~/AdminLTE/dist/img/user.svg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Reviewers
                                            <small><i class="fa fa-clock-o"></i> 2 days</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li>
                @if (User.IsInRole("Parent"))
                {
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">@Html.Partial("_AnnouncementCounter")</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have (@Html.Partial("_AnnouncementCounter")) New Announcements</li>
                            <li>
                                <ul class="menu">
                                    <a href="@Url.Action("pIndex", "Announcement")">
                                        <span class="label label-danger"><i class="icon_book_alt"></i></span>
                                        View all Announcements

                                    </a>
                                </ul>
                            </li>

                        </ul>
                    </li>
                }
                @if (User.IsInRole("admin"))
                {
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning"> @Html.Partial("_LeaveRequestCounter")</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have (@Html.Partial("_LeaveRequestCounter"))Total leave requests</li>
                            <li>
                                <ul class="menu">
                                    <li>
                                        <a href="@Url.Action("index", "Leave")">
                                            <span class="label label-danger"><i class="icon_book_alt"></i></span>
                                            View all Leave requests

                                        </a>
                                    </li>

                                </ul>
                            </li>

                        </ul>
                    </li>
                    <li>

                        @{Html.RenderAction("CartSummary", "ShoppingCart");}

                    </li>
                }
                @if (User.IsInRole("Teacher"))
                {
                    <li>
                        @{Html.RenderAction("CartSummary", "ShoppingCart");}
                    </li>
                }

                @Html.Partial("_LoginPartial")
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

Template.MVC5/Views/shared/_Inbox.cshtml
@{
/**/
//Html.RenderAction("InboxCount", "EmailUs");
}

Template.MVC5/Views/shared/_Layout2.cshtml
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page -ABANTWANA</title>
    <link href="/Content/bootstrap-darkly.css" rel="stylesheet">
    <link href="/Content/site.css" rel="stylesheet">
    <link href="~/Content200/Content/bootstrap-darkly.css" rel="stylesheet"
    <link href="~/Content200/Content/Site.css" rel="stylesheet" />
    <script src="/Scripts/modernizr-2.6.2.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


</head>
<body @*bgcolor="blue"*@>
    <style>
        body {
            background-size: cover;
            background-image: url('../../Content/books-oct16.jpg');
        }

        .navbar-inverse {
            background-color: rgba(0,0,0,0.5)
        }

            .navbar-inverse .navbar-nav > li > a:hover,
            .navbar-inverse .navbar-nav > li > a:focus {
                background-color: orange;
            }

        .big-img {
            height: 325px;
            object-fit: cover;
        }

        .header-font {
            font-family: "Josefin Slab","Helvetica Neue",Helvetica,Arial,sans-serif;
            color: #fd1506;
        }

        .fa-facebook {
            color: #3b5998;
        }

        .fa-linkedin {
            color: #0077B5;
        }

        .fa-twitter {
            color: #4099FF;
        }

        .fa-google {
            color: #d34836;
        }

        .bg-primary {
            background-color: #000 !important;
        }

        .bg-circle {
            display: inline-block;
            width: 60px;
            height: 60px;
            padding: 14px 4px;
            color: #ececec;
            text-align: center;
            border-radius: 50%;
        }

        .bg-circle-outline {
            width: 50px;
            height: 50px;
            color: smoke;
            padding: 8px 2px;
            border: 2px solid;
            border-color: smoke;
            border-radius: 50%;
        }


        .bg-circle a, a:hover, .media a:focus {
            text-decoration: none !important;
            outline: none;
            color: #ececec;
        }

        .bg-circle-outline a, a:hover, .media a:focus {
            text-decoration: none !important;
            outline: none;
            color: #ececec;
        }

        .footer {
            background: #EDEFF1;
            height: auto;
            padding-bottom: 30px;
            position: relative;
            width: 100%;
            border-bottom: 1px solid #CCCCCC;
            border-top: 1px solid #DDDDDD;
            position: fixed;
        }

            .footer p {
                margin: 0;
            }

            .footer img {
                max-width: 100%;
            }

            .footer h3 {
                border-bottom: 1px solid #BAC1C8;
                color: #54697E;
                font-size: 18px;
                font-weight: 600;
                line-height: 27px;
                padding: 40px 0 10px;
                text-transform: uppercase;
            }

            .footer ul {
                font-size: 13px;
                list-style-type: none;
                margin-left: 0;
                padding-left: 0;
                margin-top: 15px;
                color: #7F8C8D;
            }

                .footer ul li a {
                    padding: 0 0 5px 0;
                    display: block;
                }

            .footer a {
                color: #78828D
            }

        body {
            background-size: cover;
            background-image: url('../../images/laptop_cup_glasses_plant_114948_2938x1953.jpg');
        }
    </style>
    <style>
        background {
            background-image: url("Content/11.jpg");
        }
    </style>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @*<img class="pull-left" src="~/Content/icon.PNG" />*@
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li><a data-modal="" href="@Url.Action("index","Home")"><i class="fa fa-home"></i>  Home</a></li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div>  @RenderBody()</div>

</body>

</html>
<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/5bd8bcb365224c2640516c7b/default';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->
</section>

Template.MVC5/Views/shared/_alerts.cshtml
@using BootstrapSupport
@if (TempData.ContainsKey(Alerts.ATTENTION))
{
    <div class="alert alert-block">
        <a class="close" data-dismiss="alert" href="#">x</a>
        <h4 class="alert-heading">Attention!</h4>
        @TempData[Alerts.ATTENTION]
    </div>
}
@foreach(string key in Alerts.ALL.Except(new[] {Alerts.ATTENTION}))
    {
        if (TempData.ContainsKey(key))
         {
             <div class="alert alert-@key">
                 <button type="button" class="close" data-dismiss="alert">x</button>
                 @TempData[key]
             </div>
         }
    }

Template.MVC5/Views/shared/_html5shiv.cshtml
   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="~/scripts/html5shiv.js"></script>
    <![endif]-->

Template.MVC5/Views/shared/_validationSummary.cshtml
@{
    // NOTE: This constant controls whether property validation failures will be excluded from the summary
    const bool ExcludePropertyFailures = true;
    var renderSummary = false;

    if (ExcludePropertyFailures)
    {
        // Here we need to figure out if there are going to be any validation failures that are not related to a property
        // If there are none found, we don't want to display the alert div

        // This logic is taken from System.Web.Mvc.Html.ValidationExtensions.GetModelStateList(HtmlHelper htmlHelper, bool excludePropertyErrors)
        // which is eventually invoked by calling @Html.ValidationSummary(ExcludePropertyFailures)
        // The call to ViewData.ModelState.TryGetValue will determine whether there are any validation failures that are not related to a property
        ModelState state;
        ViewData.ModelState.TryGetValue(ViewData.TemplateInfo.HtmlFieldPrefix, out state);

        if (state != null)
        {
            renderSummary = true;
        }
    }
    else
    {
        if (ViewData.ModelState.Any(x => x.Value.Errors.Any()))
        {
            renderSummary = true;
        }
    }

    if (renderSummary)
    {
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">&times;</a>
            @Html.ValidationSummary(ExcludePropertyFailures)
        </div>
    }
}